#!/usr/bin/env bash

# Export 'SHELL' to child processes.
# Programs such as 'screen' honor it and otherwise use /bin/sh.
export SHELL

if [[ $- != *i* ]] || [[ $TERM == "dumb" ]]; then
  [[ -n "$SSH_CLIENT" ]] && source /etc/profile
fi

dir="$(realpath ~/.local/share/chezmoi/internal/bash)"

# Load the internal startup script
source "$dir/startup.sh"
source "$dir/isinteractive.sh"
__startup_init

source "$dir/dotenv.sh"

# Store the files to auto-load
autoload_files=($dir/autoload/*.sh)

for file in "${autoload_files[@]}"; do
  source "$file"
done

__startup_message "${autoload_files[@]}"
